INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (1, '상의');
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (2, '하의');

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (3, '반팔 티셔츠', 1);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (4, '긴팔 티셔츠', 1);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (5, '셔츠', 1);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (6, '바지', 2);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (7, '치마', 2);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (8, '슬랙스', 6);