INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (1, '상의');
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (2, '하의');
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (3, '아우터');
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (4, '가방');
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (5, '쥬얼리');

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (6, '티셔츠', 1);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (7, '긴팔 티셔츠', 6);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (8, '반팔 티셔츠', 6);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (9, '셔츠', 1);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (10, '바지', 2);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (11, '슬랙스', 10);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (12, '치마', 2);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (13, '코트', 3);
INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (14, '점퍼', 3);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME, PARENT_ID) VALUES (15, '팔찌', 5);